version: 2.1
orbs:
  compare-url: iynere/compare-url@1.2.0
jobs:
  build:
    docker:
    - image: circleci/node:12.9.1-browsers
    steps:
    - checkout
    - run: echo "hello world testing version"
    - run: pwd
